# A sample TravisCI configuration file that checks whether
# the current commit message is good or not. Adjust accordingly.
language: python

python:
  - "3.6"

if: type != pull_request

cache:
  directories:
    - $HOME/nltk_data

install:
  - pip3 install textblob
  - python3 -m textblob.download_corpora
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --all

script:
  # Run the unit tests (you probably don't need to run this in your CI)
  - pytest bad_commit_message_blocker_tests.py
  # Verify that all commit messages in current branch abide by the best practices
  - bash verify_commit_messages_in_branch.sh
